{
  posts(stage: PUBLISHED, orderBy: date_DESC) {
    title
    slug
    excerpt
    date
    coverImage {
      url(transformation: {image: {resize: {width: 600}}, document: {output: {format: webp}}})
    }
    category {
      title
      coverImage {
        url(transformation: {image: {resize: {height: 60}}, document: {output: {format: webp}}})
      }
    }
    author {
      name
      picture {
        url(transformation: {image: {resize: {height: 60}}, document: {output: {format: webp}}})
      }
    }
  }
}
