query getFeaturedPosts {
  posts(first: 4, where: {tags_contains_all: "featured"}, stage: PUBLISHED) {
    title
    slug
    date
    coverImage {
      url(transformation: {image: {resize: {width: 300}}})
    }
    category {
      title
      coverImage {
        url(transformation: {image: {resize: {height: 60}}})
      }
    }
    author {
      name
      picture {
        url(transformation: {image: {resize: {height: 60}}})
      }
    }
  }
}
