{
  posts(first: 4, stage: PUBLISHED, orderBy: date_DESC) {
    title
    slug
    excerpt
    date
    coverImage {
      url(transformation: {image: {resize: {width: 600}}})
    }
    category {
      title
      coverImage {
        url(transformation: {image: {resize: {height: 60}}})
      }
    }
    author {
      name
      picture {
        url(transformation: {image: {resize: {height: 60}}})
      }
    }
  }
}
