query getShowcasePost {
  postsConnection(first: 1, where: {tags_contains_all: "showcase"}, stage: PUBLISHED) {
    edges {
      node {
        title
        slug
        date
        coverImage {
          url(transformation: {image: {resize: {width: 300}}})
        }
        category {
          title
          coverImage {
            url(transformation: {image: {resize: {height: 60}}})
          }
        }
        author {
          name
          picture {
            url(transformation: {image: {resize: {height: 60}}})
          }
        }
      }
    }
  }
}
