{
  topics(first: 4, stage: PUBLISHED) {
    title
    slug
    coverImage {
      url(transformation: {image: {resize: {width: 200}}, document: {output: {format: webp}}})
    }
    posts {
      id
    }
  }
}
