query getTopic($slug: String!) {
  topic(stage: PUBLISHED, where: {slug: $slug}) {
    title
    slug
    coverImage {
      url
    }
    posts(orderBy: date_DESC) {
      title
      slug
      date
      excerpt
      author {
        name
        picture {
          url(transformation: {image: {resize: {height: 60}}, document: {output: {format: webp}}})
        }
      }
      category {
        title
        slug
        coverImage {
          url(transformation: {image: {resize: {height: 60}}, document: {output: {format: webp}}})
        }
      }
      coverImage {
        url(transformation: {image: {resize: {width: 600}}, document: {output: {format: webp}}})
      }
    }
  }
}